### ISSUE TITLE
Setup: Build and deploy flutter web app(flutter web auto delpoy using github pages)

### ISSUE THREAD

**Issue by woog2roid** [RememberMe-2024-SolutionChallenge/rememberme-client#1]
``` yml
Build and deploy flutter web app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh_pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

- You shoud watch out about routing
  - maybe the home url is not index(/) in github pages because only the "NAME.github.io" repository has the index url.
  - 이름.github.io만 index(/) url을 갖고 아마 지금 같은 경우에는 rememberme.github.io/rememberme-client가 home 라우트 일 거라 오류가 있을 수 있습니다. 이 부분 유의하시고 문제 생기면 지우거나, 나중에 구글 도메인 지원오면 확인하는 방향으로 갑시다.
